# Generated by Django 6.0.6 on 2026-06-29 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_quoterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
    ]
